### ISSUE TITLE
python3-pyqt5 error but its installed

### ISSUE THREAD

**Issue by willemkuijpers** [SECFORCE/sparta#120]
sudo sparta
[-] Import failed. PyQt5 library not found. 
Try installing it with: apt install python3-pyqt5
No module named PyQt5
root@lappie:~/Downloads# sudo apt install python3-sqlalchemy python3-pyqt5 wkhtmltopdf
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-pyqt5 is already the newest version (5.14.2+dfsg-1+b1).
python3-sqlalchemy is already the newest version (1.3.15+ds1-1).
wkhtmltopdf is already the newest version (0.12.5-1+b2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by st3r30byt3** [comment]
Hi Willem.

Maybe python3 is not your default interpreter. I pushed a change to dev so that the sparta file you copy to /usr/bin invokes python3 explicitly.

Maybe give it a try?

**Comment by X-n3t** [comment]
I have problems with dev version in Parrot OS:

dpkg: error al procesar el paquete firmware-b43legacy-installer (--configure):
 el subproceso instalado paquete firmware-b43legacy-installer script post-installation devolvió 
el código de salida de error 123
Procesando disparadores para initramfs-tools (0.137) ...
update-initramfs: Generating /boot/initrd.img-5.5.0-1parrot1-amd64
pigz: abort: write error on <stdout> (No space left on device)
E: mkinitramfs failure cpio 141 pigz 28
update-initramfs: failed for /boot/initrd.img-5.5.0-1parrot1-amd64 with 1.
dpkg: error al procesar el paquete initramfs-tools (--configure):
 el subproceso instalado paquete initramfs-tools script post-installation devolvió el código de 
salida de error 1
Se encontraron errores al procesar:
 firmware-b43-installer
 firmware-b43legacy-installer
 initramfs-tools
needrestart is being skipped since dpkg has failed
Scanning application launchers
Removing duplicate launchers from Debian
Launchers are updated
E: Sub-process /usr/bin/dpkg returned an error code (1)
                                                                                                
╭─░▒▓      /usr/share/sparta    30s  root@xOS  ✘ 100 ▓▒░
╰─ sparta
[-] Import failed. SQLAlchemy library not found. 
Try installing it with: apt install python3-sqlalchemy
No module named 'sqlalchemy.orm'

**Comment by st3r30byt3** [comment]
Closing for lack of feedback.
