### ISSUE TITLE
Elixir - not found

### ISSUE THREAD

**Issue by bonda007** [SECFORCE/sparta#46]
Hello, i went over all of the issue related to the Elixir not found problem with no success

can you please help ?

lool@ubuntu:/usr/bin$ sparta
[-] Import failed. Elixir library not found. 
Try installing it with: apt-get install python-elixir

**Comment by mw3demo** [comment]
Don't mean to stat the obvious, but have you
    apt-get install python-elixir

?

**Comment by st3r30byt3** [comment]
Hi! Many people have ran into this problem in the past and it should be fixed in the latest version.
I suppose you have the latest version?

Other than what mw3demo said (thanks) can you try:
sudo pip install SQLAlchemy --upgrade

Make sure you also installed all the dependencies mentioned in the Readme. Alternatively, if it's an option for you, SPARTA is now included in the latest version of Kali Linux :)
