### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by exploitprotocol** [SECFORCE/sparta#56]
Hi,

First of all, it is really awesome and useful tool :+1: 

I would like to know if you are going to provide support for windows in future. I would like to include this in [Pentestbox](https://pentestbox.com) .

Thanks
Aditya Agrawal

**Comment by st3r30byt3** [comment]
Hi Aditya. Thanks for the positive feedback!

While it would be great to have SPARTA included in Pentestbox, I am afraid that this is something we do not plan to do in the future because not only would it involve massive changes to the way SPARTA works but also because SPARTA relies on having several tools installed, uses shell scripts and overall operates in a very 'Linux way'. :)
