### ISSUE TITLE
Running (port action) nmap scripts on port, on a port already found, causes auto jobs to run again

### ISSUE THREAD

**Issue by kildonan5** [SECFORCE/sparta#88]
As the title suggest, scheduled jobs (under the "scheduler settings" in the config file) run again after running the port action "nmap=Run nmap (scripts) on port". I assume this is because the port is being RE-added to the port list but not sure.

To recreate;

- Setup an automatic job on a port (i.e. enum4linux on SMB port). 
- Run a staged nmap scan where SMB is discovered and added to the port list. Ensure enum4linux kicks off as an automatic/scheduled action.
- Right click the SMB port and click "Run nmap (scripts) on port"
- Watch as enum4linux automatically starts again.

Expected action:
- Running the "nmap" port action should not cause automatic/scheduled scripts to kick off again.

**Comment by rewardone** [comment]
The scheduler function in the Controller does not have a way to determine if actions have already been taken on a port (ie if an automatic/scheduled script has already been run). 

A separate tracker or table in the DB would probably have to be created to track actions taken on IPs and ports and a check implemented in the scheduler function. 

Do you have code for a proposed solution?

**Comment by st3r30byt3** [comment]
Hi. Thanks for the feedback.

This was a design decision. It also happens if you decide to run nmap again on multiple ports. 

We assumed that if you are scanning the same host again it's because the previous results are outdated so we would rather keep the latest results. You can always disable automated attacks if you want re-scan.

Alternatively, you can modify the original nmap command in the conf file to include script scanning (-sC).
