### ISSUE TITLE
SSL screenshots 

### ISSUE THREAD

**Issue by dicipulus** [SECFORCE/sparta#9]
Compiled Cuttycapt as per your instructions. That worked well, however screenshots do not work within the Sparta for certs that are based on URL and not IP. I looked in the config file to try to insert '--insecure' since that seems to work from the command-line with Cuttycapt, but wasn't able to find the command for Cuttycapt, just the pathway which I pointed to my new Cuttycapt.

**Comment by st3r30byt3** [comment]
Thanks for the feedback. Currently, the cutycapt command is hard-coded and not in configuration file because quite a lot of logic was required for the screenshooter functionality and changing the command in the wrong way could break it. We have asked the (awesome) Kali Linux guys to update cutycapt to the latest version so that we can simply include the --insecure flag in our command which would solve most problems. In the meantime we are considering other alternatives.

If you are a bit familiar with programming, a temporary solution would be to edit the app/auxiliary.py file and change the command in line 281.

**Comment by dicipulus** [comment]
Perfect, that line and .py file is exactly what I needed to know!

**Comment by st3r30byt3** [comment]
Awesome! ;)
